"""Define public normalized performance comparison column names.

These constants are intentionally public. They are the canonical schema
vocabulary shared by loaders, comparison logic, reports, tests, and downstream
callers that need stable output column names.

Detailed unqualified monetary fields use the row ``currency``. Detailed
``base_`` monetary fields use portfolio ``base_currency``. Monetary fields in
portfolio/security performance datasets are inherently portfolio-base values.
FX rates use explicit ``from_currency`` and ``to_currency`` units.
"""

__all__ = [
    "PORTFOLIO_PERFORMANCE",
    "SECURITY_PERFORMANCE",
    "SPLITS",
    "FX_RATES",
    "TRANSACTIONS",
    "HOLDINGS",
    "SECURITY_MASTER",
    "PORTFOLIO_ID",
    "SECURITY_ID",
    "FROM_DATE",
    "THRU_DATE",
    "RATE_DATE",
    "SPLIT_DATE",
    "TRANSACTION_DATE",
    "ORIGINAL_COST_DATE",
    "SETTLEMENT_DATE",
    "HOLDING_DATE",
    "PORTFOLIO_RETURN",
    "SECURITY_RETURN",
    "PRICE",
    "FX_RATE",
    "FROM_CURRENCY",
    "TO_CURRENCY",
    "WEIGHT",
    "CONTRIBUTION",
    "PORTFOLIO_NAME",
    "SECURITY_NAME",
    "TICKER",
    "CUSIP",
    "ISIN",
    "COUNTRY",
    "SECTOR",
    "INDUSTRY",
    "ASSET_CLASS",
    "ASSET_CLASS_CODE",
    "ASSET_CLASS_NAME",
    "SECTOR_CODE",
    "COUNTRY_CODE",
    "BEGIN_MARKET_VALUE",
    "END_MARKET_VALUE",
    "MARKET_VALUE",
    "BASE_MARKET_VALUE",
    "BASE_CURRENCY",
    "FLOW",
    "INCOME",
    "GAIN_LOSS",
    "PERIOD_ID",
    "CURRENCY",
    "RATE_SOURCE",
    "RATE_TYPE",
    "SPLIT_FACTOR",
    "TRANSACTION_ID",
    "TRANSACTION_CODE",
    "SECURITY_TYPE",
    "TRANSACTION_SECURITY_TYPE",
    "SOURCE_DESTINATION_TYPE",
    "SOURCE_DESTINATION_SYMBOL",
    "SPECIAL_SECURITY_TYPE",
    "SPECIAL_SECURITY_SYMBOL",
    "TRANSACTION_CATEGORY",
    "CASH_FLOW_SIGN",
    "PERFORMANCE_FLOW_SIGN",
    "TRANSACTION_SEMANTICS_SOURCE",
    "QUANTITY",
    "AMOUNT",
    "BASE_AMOUNT",
    "BASE_ACCRUED",
    "LOCAL_EXPOSURE",
    "COMMISSION",
    "BROKER",
    "COST",
    "ORIGINAL_COST",
    "ACCRUED",
    "PORTFOLIO_PERFORMANCE_REQUIRED_COLUMNS",
    "PORTFOLIO_PERFORMANCE_OPTIONAL_COLUMNS",
    "PORTFOLIO_PERFORMANCE_COLUMNS",
    "SECURITY_PERFORMANCE_REQUIRED_COLUMNS",
    "SECURITY_PERFORMANCE_OPTIONAL_COLUMNS",
    "SECURITY_PERFORMANCE_COLUMNS",
    "SPLITS_REQUIRED_COLUMNS",
    "SPLITS_OPTIONAL_COLUMNS",
    "SPLITS_COLUMNS",
    "FX_RATES_REQUIRED_COLUMNS",
    "FX_RATES_OPTIONAL_COLUMNS",
    "FX_RATES_COLUMNS",
    "TRANSACTIONS_REQUIRED_COLUMNS",
    "TRANSACTIONS_PERFORMANCE_CALCULATION_REQUIRED_COLUMNS",
    "TRANSACTIONS_OPTIONAL_COLUMNS",
    "TRANSACTIONS_COLUMNS",
    "HOLDINGS_REQUIRED_COLUMNS",
    "HOLDINGS_PERFORMANCE_CALCULATION_REQUIRED_COLUMNS",
    "HOLDINGS_OPTIONAL_COLUMNS",
    "HOLDINGS_COLUMNS",
    "SECURITY_MASTER_REQUIRED_COLUMNS",
    "SECURITY_MASTER_OPTIONAL_COLUMNS",
    "SECURITY_MASTER_COLUMNS",
]

PORTFOLIO_PERFORMANCE = "portfolio_performance"
SECURITY_PERFORMANCE = "security_performance"
SPLITS = "splits"
FX_RATES = "fx_rates"
TRANSACTIONS = "transactions"
HOLDINGS = "holdings"
SECURITY_MASTER = "security_master"

PORTFOLIO_ID = "portfolio_id"
SECURITY_ID = "security_id"
FROM_DATE = "from_date"
THRU_DATE = "thru_date"
RATE_DATE = "rate_date"
SPLIT_DATE = "split_date"
TRANSACTION_DATE = "transaction_date"
ORIGINAL_COST_DATE = "original_cost_date"
SETTLEMENT_DATE = "settlement_date"
HOLDING_DATE = "holding_date"
PORTFOLIO_RETURN = "portfolio_return"
SECURITY_RETURN = "security_return"
PRICE = "price"
FX_RATE = "fx_rate"
FROM_CURRENCY = "from_currency"
TO_CURRENCY = "to_currency"
WEIGHT = "weight"
CONTRIBUTION = "contribution"
PORTFOLIO_NAME = "portfolio_name"
SECURITY_NAME = "security_name"
TICKER = "ticker"
CUSIP = "cusip"
ISIN = "isin"
COUNTRY = "country"
SECTOR = "sector"
INDUSTRY = "industry"
ASSET_CLASS = "asset_class"
ASSET_CLASS_CODE = "asset_class_code"
ASSET_CLASS_NAME = "asset_class_name"
SECTOR_CODE = "sector_code"
COUNTRY_CODE = "country_code"
BEGIN_MARKET_VALUE = "begin_market_value"
END_MARKET_VALUE = "end_market_value"
MARKET_VALUE = "market_value"
BASE_MARKET_VALUE = "base_market_value"
BASE_CURRENCY = "base_currency"
FLOW = "flow"
INCOME = "income"
GAIN_LOSS = "gain_loss"
PERIOD_ID = "period_id"
CURRENCY = "currency"
RATE_SOURCE = "rate_source"
RATE_TYPE = "rate_type"
SPLIT_FACTOR = "split_factor"
TRANSACTION_ID = "transaction_id"
TRANSACTION_CODE = "transaction_code"
SECURITY_TYPE = "security_type"
TRANSACTION_SECURITY_TYPE = "transaction_security_type"
SOURCE_DESTINATION_TYPE = "source_destination_type"
SOURCE_DESTINATION_SYMBOL = "source_destination_symbol"
SPECIAL_SECURITY_TYPE = "special_security_type"
SPECIAL_SECURITY_SYMBOL = "special_security_symbol"
TRANSACTION_CATEGORY = "transaction_category"
CASH_FLOW_SIGN = "cash_flow_sign"
PERFORMANCE_FLOW_SIGN = "performance_flow_sign"
TRANSACTION_SEMANTICS_SOURCE = "transaction_semantics_source"
QUANTITY = "quantity"
AMOUNT = "amount"
BASE_AMOUNT = "base_amount"
BASE_ACCRUED = "base_accrued"
LOCAL_EXPOSURE = "local_exposure"
COMMISSION = "commission"
BROKER = "broker"
COST = "cost"
ORIGINAL_COST = "original_cost"
ACCRUED = "accrued"

PORTFOLIO_PERFORMANCE_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    FROM_DATE,
    THRU_DATE,
    PORTFOLIO_RETURN,
)

PORTFOLIO_PERFORMANCE_OPTIONAL_COLUMNS = (
    BASE_CURRENCY,
)

PORTFOLIO_PERFORMANCE_COLUMNS = (
    *PORTFOLIO_PERFORMANCE_REQUIRED_COLUMNS,
    *PORTFOLIO_PERFORMANCE_OPTIONAL_COLUMNS,
)

SECURITY_PERFORMANCE_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    SECURITY_ID,
    FROM_DATE,
    THRU_DATE,
    SECURITY_RETURN,
)

SECURITY_PERFORMANCE_OPTIONAL_COLUMNS: tuple[str, ...] = ()

SECURITY_PERFORMANCE_COLUMNS = (
    *SECURITY_PERFORMANCE_REQUIRED_COLUMNS,
    *SECURITY_PERFORMANCE_OPTIONAL_COLUMNS,
)

SPLITS_REQUIRED_COLUMNS = (
    SECURITY_ID,
    SPLIT_DATE,
    SPLIT_FACTOR,
)

SPLITS_OPTIONAL_COLUMNS = (
    SECURITY_NAME,
    TICKER,
)

SPLITS_COLUMNS = (
    *SPLITS_REQUIRED_COLUMNS,
    *SPLITS_OPTIONAL_COLUMNS,
)

FX_RATES_REQUIRED_COLUMNS = (
    FROM_CURRENCY,
    TO_CURRENCY,
    RATE_DATE,
    FX_RATE,
)

FX_RATES_OPTIONAL_COLUMNS = (
    PORTFOLIO_ID,
    LOCAL_EXPOSURE,
    RATE_SOURCE,
    RATE_TYPE,
)

FX_RATES_COLUMNS = (
    *FX_RATES_REQUIRED_COLUMNS,
    *FX_RATES_OPTIONAL_COLUMNS,
)

TRANSACTIONS_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    SECURITY_ID,
    TRANSACTION_DATE,
)

TRANSACTIONS_PERFORMANCE_CALCULATION_REQUIRED_COLUMNS = (
    *TRANSACTIONS_REQUIRED_COLUMNS,
    TRANSACTION_CODE,
    AMOUNT,
)

TRANSACTIONS_OPTIONAL_COLUMNS = (
    TRANSACTION_ID,
    SETTLEMENT_DATE,
    TRANSACTION_CODE,
    ORIGINAL_COST_DATE,
    TRANSACTION_SECURITY_TYPE,
    SOURCE_DESTINATION_TYPE,
    SOURCE_DESTINATION_SYMBOL,
    SPECIAL_SECURITY_TYPE,
    SPECIAL_SECURITY_SYMBOL,
    TRANSACTION_CATEGORY,
    CASH_FLOW_SIGN,
    PERFORMANCE_FLOW_SIGN,
    TRANSACTION_SEMANTICS_SOURCE,
    QUANTITY,
    PRICE,
    AMOUNT,
    BASE_AMOUNT,
    COMMISSION,
    CURRENCY,
    BASE_CURRENCY,
    BROKER,
    ORIGINAL_COST,
)

TRANSACTIONS_COLUMNS = (
    *TRANSACTIONS_REQUIRED_COLUMNS,
    *TRANSACTIONS_OPTIONAL_COLUMNS,
)

HOLDINGS_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    SECURITY_ID,
    HOLDING_DATE,
)

HOLDINGS_PERFORMANCE_CALCULATION_REQUIRED_COLUMNS = (
    *HOLDINGS_REQUIRED_COLUMNS,
    MARKET_VALUE,
)

HOLDINGS_OPTIONAL_COLUMNS = (
    QUANTITY,
    PRICE,
    MARKET_VALUE,
    BASE_MARKET_VALUE,
    BASE_ACCRUED,
    COST,
    ACCRUED,
    CURRENCY,
    BASE_CURRENCY,
)

HOLDINGS_COLUMNS = (
    *HOLDINGS_REQUIRED_COLUMNS,
    *HOLDINGS_OPTIONAL_COLUMNS,
)

SECURITY_MASTER_REQUIRED_COLUMNS = (SECURITY_ID,)

SECURITY_MASTER_OPTIONAL_COLUMNS = (
    SECURITY_NAME,
    TICKER,
    CUSIP,
    ISIN,
    SECURITY_TYPE,
    ASSET_CLASS_CODE,
    ASSET_CLASS_NAME,
    SECTOR_CODE,
    SECTOR,
    COUNTRY_CODE,
    COUNTRY,
    CURRENCY,
)

SECURITY_MASTER_COLUMNS = (
    *SECURITY_MASTER_REQUIRED_COLUMNS,
    *SECURITY_MASTER_OPTIONAL_COLUMNS,
)
