"""Render the human-readable transaction row matrix from its YAML contract."""

from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, Final

import yaml


_REPO_ROOT: Final = Path(__file__).resolve().parents[1]
_DEFAULT_CONTRACT_PATH: Final = (
    _REPO_ROOT / "docs" / "axys_apx" / "contracts" / "transaction_semantics_matrix.yaml"
)
_DEFAULT_OUTPUT_PATH: Final = (
    _REPO_ROOT / "docs" / "axys_apx" / "contracts" / "transaction_semantics_matrix.md"
)
_START_MARKER: Final = "<!-- BEGIN GENERATED TRANSACTION ROWS -->"
_END_MARKER: Final = "<!-- END GENERATED TRANSACTION ROWS -->"


def main(argv: Sequence[str] | None = None) -> int:
    """Render the matrix or verify that the checked-in Markdown is current.

    Args:
        argv: Optional command-line arguments. Defaults to process arguments.

    Returns:
        Process-style exit code. ``1`` means ``--check`` found stale output.
    """
    args = _parse_args(argv)
    contract = _load_mapping(args.contract)
    current = args.output.read_text(encoding="utf-8")
    rendered = _replace_generated_rows(current, _render_rows(contract))

    if args.check:
        if current != rendered:
            print(f"{args.output} is stale; rerun {Path(__file__).as_posix()}.")
            return 1
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", type=Path, default=_DEFAULT_CONTRACT_PATH)
    parser.add_argument("--output", type=Path, default=_DEFAULT_OUTPUT_PATH)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def _load_mapping(path: Path) -> Mapping[str, Any]:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(loaded, Mapping):
        raise ValueError(f"Expected a YAML mapping in {path}.")
    return loaded


def _replace_generated_rows(document: str, generated_rows: str) -> str:
    if document.count(_START_MARKER) != 1 or document.count(_END_MARKER) != 1:
        raise ValueError("Transaction matrix must contain one generated-row marker pair.")
    before, remainder = document.split(_START_MARKER, 1)
    _, after = remainder.split(_END_MARKER, 1)
    return f"{before}{_START_MARKER}\n{generated_rows}\n{_END_MARKER}{after}"


def _render_rows(contract: Mapping[str, Any]) -> str:
    rows = _mapping(contract, "rows")
    required_codes = _string_sequence(contract, "required_matrix_codes")
    coverage_statuses = _mapping(contract, "coverage_statuses")
    if set(rows) != set(required_codes):
        raise ValueError("rows and required_matrix_codes must contain the same codes.")

    lines = [
        "<!-- Generated by scripts/render_transaction_semantics_matrix.py. -->",
        "| Code | Observed meaning | PPAR categories | Cash-flow signs | "
        "Performance-flow signs | Required evidence | IMEX | REP | Coverage | "
        "Fixtures | Coverage notes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for code in required_codes:
        metadata = _mapping(rows, code)
        coverage_key = _required_string(metadata, "coverage_status")
        coverage = _required_string(coverage_statuses, coverage_key)
        values = (
            f"`{code}`",
            _required_string(metadata, "observed_meaning"),
            _code_values(metadata, "ppar_categories"),
            _code_values(metadata, "cash_flow_signs"),
            _code_values(metadata, "performance_flow_signs"),
            _code_values(metadata, "required_evidence"),
            _display_identifier(_required_string(metadata, "imex_confidence")),
            _display_identifier(_required_string(metadata, "rep_confidence")),
            coverage,
            _code_values(metadata, "fixtures"),
            _required_string(metadata, "coverage_notes"),
        )
        lines.append("| " + " | ".join(_escape_table_text(value) for value in values) + " |")
    return "\n".join(lines)


def _mapping(mapping: Mapping[str, Any], key: str) -> Mapping[str, Any]:
    value = mapping.get(key)
    if not isinstance(value, Mapping):
        raise ValueError(f"Expected {key!r} to be a mapping.")
    return value


def _string_sequence(mapping: Mapping[str, Any], key: str) -> tuple[str, ...]:
    value = mapping.get(key)
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        raise ValueError(f"Expected {key!r} to be a sequence.")
    result = tuple(str(item) for item in value)
    if not all(result):
        raise ValueError(f"Expected {key!r} to contain nonblank strings.")
    return result


def _required_string(mapping: Mapping[str, Any], key: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"Expected {key!r} to be a nonblank string.")
    return value.strip()


def _code_values(mapping: Mapping[str, Any], key: str) -> str:
    return ", ".join(f"`{value}`" for value in _string_sequence(mapping, key))


def _display_identifier(value: str) -> str:
    return value.replace("_", " ").title()


def _escape_table_text(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", "<br>")


if __name__ == "__main__":
    raise SystemExit(main())
