"""Show and run the standard Performance Auditing workflow from Python.

This script intentionally expands the work performed by ``ppar audit`` instead
of calling the CLI. As generated by ``ppar setup``, it creates the same default
portfolio and security reports. Edit the visible Python below when you want to
customize the standard workflow.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys
from typing import Any

# Project imports
from ppar.errors import PpaError
from ppar.performance_comparison import (
    compare_snapshots,
    write_performance_comparison_report_bundle,
)
from ppar.performance_comparison.specification import (
    PORTFOLIO_COMPARISON_LEVEL,
    SECURITY_COMPARISON_LEVEL,
)


# Anchor paths to this setup folder so the script can be run from any current
# working directory.
SITE_DIRECTORY: Path = Path(__file__).resolve().parent
SPECIFICATIONS_PATH: Path = SITE_DIRECTORY / "ppar.yaml"


@dataclass(frozen=True)
class ReportSpec:
    """Describe one Performance Auditing report to write.

    Attributes:
        comparison_level: Report level passed to the PPAR comparison engine.
        title: Workbook and HTML report title.
        output_directory: Folder that receives the report package.
    """

    comparison_level: str
    title: str
    output_directory: Path


REPORTS: tuple[ReportSpec, ...] = (
    ReportSpec(
        comparison_level=PORTFOLIO_COMPARISON_LEVEL,
        title="Portfolio Performance Auditing Report",
        output_directory=SITE_DIRECTORY / "output" / PORTFOLIO_COMPARISON_LEVEL,
    ),
    ReportSpec(
        comparison_level=SECURITY_COMPARISON_LEVEL,
        title="Security Performance Auditing Report",
        output_directory=SITE_DIRECTORY / "output" / SECURITY_COMPARISON_LEVEL,
    ),
)


def main(argv: list[str] | None = None) -> int:
    """Create the portfolio and security Performance Auditing reports.

    Args:
        argv: Optional command-line arguments excluding the script name.

    Returns:
        Process exit code. ``0`` indicates that the requested reports were
        written.
    """
    args = _argument_parser().parse_args(argv)
    selected_reports = (
        REPORTS if args.report == "both" else tuple(
            report for report in REPORTS if report.comparison_level == args.report
        )
    )
    workbook_paths: list[Path] = []
    security_skipped = False
    for report in selected_reports:
        try:
            workbook_paths.append(_write_report(report))
        except PpaError as error:
            if args.report == "both" and _is_missing_security_data(error):
                security_skipped = True
                continue
            print(f"Report failed: {error}", file=sys.stderr)
            return 1

    print("Open these files to review Performance Auditing output:")
    for workbook_path in workbook_paths:
        print(f"  {workbook_path}")
    if security_skipped:
        print()
        print("Security output skipped because files.security_performance is not available.")
    return 0


def _argument_parser() -> argparse.ArgumentParser:
    """Return arguments equivalent to the ``ppar audit`` options."""
    parser = argparse.ArgumentParser(
        description="Run Performance Auditing from this Python setup file.",
    )
    parser.add_argument(
        "--report",
        choices=(PORTFOLIO_COMPARISON_LEVEL, SECURITY_COMPARISON_LEVEL, "both"),
        default="both",
        help="Report family to generate. Defaults to both.",
    )
    return parser


def _write_report(report: ReportSpec) -> Path:
    """Write one Performance Auditing report and return its workbook path."""
    # ``compare_snapshots`` reads the two snapshot folders named in ``ppar.yaml``
    # and returns normalized finding rows for changed performance and source
    # data. Put mapping, transaction, and report decisions in the YAML.
    findings: Any = compare_snapshots(
        SPECIFICATIONS_PATH,
        comparison_level=report.comparison_level,
    )

    # The report bundle turns those findings into the review workbook. The HTML
    # version of the workbook is written alongside it.
    bundle_paths: dict[str, Path] = write_performance_comparison_report_bundle(
        findings,
        report.output_directory,
        title=report.title,
        include_workbook=True,
        comparison_path=SPECIFICATIONS_PATH,
        comparison_level=report.comparison_level,
    )
    return bundle_paths["review_workbook"]


def _is_missing_security_data(error: PpaError) -> bool:
    """Return whether security output failed because secperf is unavailable."""
    message = str(error)
    return (
        "files.security_performance" in message
        and ("is required" in message or "is missing" in message)
    )


if __name__ == "__main__":
    raise SystemExit(main())
