"""Define normalized performance comparison column names."""

PORTFOLIO_PERFORMANCE = "portfolio_performance"
SECURITY_PERFORMANCE = "security_performance"
SECURITY_MASTER = "security_master"
PRICES = "prices"
FX_RATES = "fx_rates"
TRANSACTIONS = "transactions"
POSITIONS = "positions"
CASH = "cash"

PORTFOLIO_ID = "portfolio_id"
SECURITY_ID = "security_id"
FROM_DATE = "from_date"
THRU_DATE = "thru_date"
PRICE_DATE = "price_date"
RATE_DATE = "rate_date"
TRANSACTION_DATE = "transaction_date"
SETTLEMENT_DATE = "settlement_date"
POSITION_DATE = "position_date"
CASH_DATE = "cash_date"
PORTFOLIO_RETURN = "portfolio_return"
SECURITY_RETURN = "security_return"
PRICE = "price"
FX_RATE = "fx_rate"
FROM_CURRENCY = "from_currency"
TO_CURRENCY = "to_currency"
WEIGHT = "weight"
CONTRIBUTION = "contribution"
PORTFOLIO_NAME = "portfolio_name"
SECURITY_NAME = "security_name"
TICKER = "ticker"
CUSIP = "cusip"
ISIN = "isin"
COUNTRY = "country"
SECTOR = "sector"
INDUSTRY = "industry"
ASSET_CLASS = "asset_class"
BEGIN_MARKET_VALUE = "begin_market_value"
END_MARKET_VALUE = "end_market_value"
MARKET_VALUE = "market_value"
FLOW = "flow"
INCOME = "income"
GAIN_LOSS = "gain_loss"
PERIOD_ID = "period_id"
CURRENCY = "currency"
PRICE_SOURCE = "price_source"
PRICE_TYPE = "price_type"
RATE_SOURCE = "rate_source"
RATE_TYPE = "rate_type"
TRANSACTION_ID = "transaction_id"
TRANSACTION_CODE = "transaction_code"
TRANSACTION_CATEGORY = "transaction_category"
CASH_FLOW_SIGN = "cash_flow_sign"
PERFORMANCE_FLOW_SIGN = "performance_flow_sign"
QUANTITY = "quantity"
AMOUNT = "amount"
COMMISSION = "commission"
BROKER = "broker"
COST = "cost"
ACCRUED = "accrued"
CASH_BALANCE = "cash_balance"

PORTFOLIO_PERFORMANCE_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    FROM_DATE,
    THRU_DATE,
    PORTFOLIO_RETURN,
)

PORTFOLIO_PERFORMANCE_OPTIONAL_COLUMNS = (
    PORTFOLIO_NAME,
    BEGIN_MARKET_VALUE,
    END_MARKET_VALUE,
    FLOW,
    INCOME,
    GAIN_LOSS,
    PERIOD_ID,
    CURRENCY,
)

PORTFOLIO_PERFORMANCE_COLUMNS = (
    *PORTFOLIO_PERFORMANCE_REQUIRED_COLUMNS,
    *PORTFOLIO_PERFORMANCE_OPTIONAL_COLUMNS,
)

SECURITY_PERFORMANCE_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    SECURITY_ID,
    FROM_DATE,
    THRU_DATE,
    SECURITY_RETURN,
)

SECURITY_PERFORMANCE_OPTIONAL_COLUMNS = (
    SECURITY_NAME,
    WEIGHT,
    CONTRIBUTION,
    BEGIN_MARKET_VALUE,
    END_MARKET_VALUE,
    INCOME,
    GAIN_LOSS,
    PERIOD_ID,
    CURRENCY,
)

SECURITY_PERFORMANCE_COLUMNS = (
    *SECURITY_PERFORMANCE_REQUIRED_COLUMNS,
    *SECURITY_PERFORMANCE_OPTIONAL_COLUMNS,
)

SECURITY_MASTER_REQUIRED_COLUMNS = (SECURITY_ID,)

SECURITY_MASTER_OPTIONAL_COLUMNS = (
    SECURITY_NAME,
    TICKER,
    CUSIP,
    ISIN,
    CURRENCY,
    COUNTRY,
    SECTOR,
    INDUSTRY,
    ASSET_CLASS,
)

SECURITY_MASTER_COLUMNS = (
    *SECURITY_MASTER_REQUIRED_COLUMNS,
    *SECURITY_MASTER_OPTIONAL_COLUMNS,
)

PRICES_REQUIRED_COLUMNS = (
    SECURITY_ID,
    PRICE_DATE,
    PRICE,
)

PRICES_OPTIONAL_COLUMNS = (
    CURRENCY,
    PRICE_SOURCE,
    PRICE_TYPE,
)

PRICES_COLUMNS = (
    *PRICES_REQUIRED_COLUMNS,
    *PRICES_OPTIONAL_COLUMNS,
)

FX_RATES_REQUIRED_COLUMNS = (
    FROM_CURRENCY,
    TO_CURRENCY,
    RATE_DATE,
    FX_RATE,
)

FX_RATES_OPTIONAL_COLUMNS = (
    RATE_SOURCE,
    RATE_TYPE,
)

FX_RATES_COLUMNS = (
    *FX_RATES_REQUIRED_COLUMNS,
    *FX_RATES_OPTIONAL_COLUMNS,
)

TRANSACTIONS_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    SECURITY_ID,
    TRANSACTION_DATE,
)

TRANSACTIONS_OPTIONAL_COLUMNS = (
    TRANSACTION_ID,
    SETTLEMENT_DATE,
    TRANSACTION_CODE,
    TRANSACTION_CATEGORY,
    CASH_FLOW_SIGN,
    PERFORMANCE_FLOW_SIGN,
    QUANTITY,
    PRICE,
    AMOUNT,
    COMMISSION,
    CURRENCY,
    BROKER,
)

TRANSACTIONS_COLUMNS = (
    *TRANSACTIONS_REQUIRED_COLUMNS,
    *TRANSACTIONS_OPTIONAL_COLUMNS,
)

POSITIONS_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    SECURITY_ID,
    POSITION_DATE,
)

POSITIONS_OPTIONAL_COLUMNS = (
    QUANTITY,
    PRICE,
    MARKET_VALUE,
    COST,
    ACCRUED,
    CURRENCY,
)

POSITIONS_COLUMNS = (
    *POSITIONS_REQUIRED_COLUMNS,
    *POSITIONS_OPTIONAL_COLUMNS,
)

CASH_REQUIRED_COLUMNS = (
    PORTFOLIO_ID,
    CASH_DATE,
)

CASH_OPTIONAL_COLUMNS = (
    CURRENCY,
    CASH_BALANCE,
    MARKET_VALUE,
)

CASH_COLUMNS = (
    *CASH_REQUIRED_COLUMNS,
    *CASH_OPTIONAL_COLUMNS,
)
