"""Show and run the standard Performance Analytics workflow from Python.

This script intentionally expands the work performed by ``ppar analytics``
instead of calling the CLI. As generated by ``ppar setup``, it reads the same
YAML settings and creates the same standard outputs. Edit the visible Python
below when you want to customize the standard workflow.
"""

from __future__ import annotations

# Python imports
from pathlib import Path
from typing import Any

# Third-party imports
import yaml

# Project imports
from ppar.analytics.attribution import Chart, View
from ppar.analytics.frequency import Frequency
from ppar.axys import AxysData
import ppar.utilities as util


# Anchor every relative path to the folder containing this script. That lets
# you run the script from any current working directory without changing paths.
SITE_DIRECTORY: Path = Path(__file__).resolve().parent
SPECIFICATIONS_PATH: Path = SITE_DIRECTORY / "ppar.yaml"


def main() -> None:
    """Create analytics output from the local setup-site CSV files.

    Returns:
        None. Review files are written to ``output/`` and listed in the
        console.
    """
    # Read the same YAML settings used by ``ppar analytics``. Keeping these
    # choices in YAML makes the unchanged script and CLI equivalent.
    settings = _load_analytics_settings()
    portfolio_code = _required_setting(settings, "portfolio")
    benchmark_code = _required_setting(settings, "benchmark")
    frequency = _frequency_from_string(str(settings.get("frequency", "quarterly")))
    output_directory = SITE_DIRECTORY / str(settings.get("output_directory", "output"))

    # ``AxysData`` uses the remaining YAML sections to locate and interpret the
    # local IMEX CSV files.
    source_data: AxysData = AxysData(SPECIFICATIONS_PATH)

    # These two portfolio objects are the inputs to attribution: one managed
    # portfolio and one benchmark. Change the codes above or in YAML as your
    # site setup evolves.
    portfolio: Any = source_data.get_portfolio(portfolio_code)
    benchmark: Any = source_data.get_portfolio(benchmark_code)

    # ``to_analytics`` calculates the return, contribution, attribution, and
    # risk data used by the review files below.
    analytics: Any = portfolio.to_analytics(benchmark, frequency=frequency)

    written_paths: list[Path] = []

    # Security attribution is useful for checking which individual positions
    # drove the active return over the selected reporting window.
    attribution_by_security: Any = analytics.get_attribution("Security")
    written_paths.append(
        _write_html(
            output_directory,
            "security_overall_attribution.html",
            attribution_by_security.to_html(View.OVERALL_ATTRIBUTION),
        )
    )

    # The default attribution level in the starter setup is sector. These HTML
    # tables are easy to inspect first because they are compact and sortable.
    attribution_by_sector: Any = analytics.get_attribution()
    for view in (View.CUMULATIVE_ATTRIBUTION, View.OVERALL_ATTRIBUTION):
        written_paths.append(
            _write_html(
                output_directory,
                f"sector_{view.name.lower()}.html",
                attribution_by_sector.to_html(view),
            )
        )

    # PNG charts are written separately so they can be used in decks, emails,
    # README files, or other materials outside the HTML tables.
    for chart in (
        Chart.OVERALL_CONTRIBUTION,
        Chart.OVERALL_ATTRIBUTION,
        Chart.SUBPERIOD_ATTRIBUTION,
        Chart.HEATMAP_ACTIVE_CONTRIBUTION,
        Chart.HEATMAP_ATTRIBUTION,
        Chart.CUMULATIVE_ATTRIBUTION,
        Chart.CUMULATIVE_RETURN,
    ):
        written_paths.append(
            _write_png(
                output_directory,
                f"sector_{chart.name.lower()}.png",
                attribution_by_sector.to_chart(chart),
            )
        )

    # Risk statistics provide a separate cross-check on the same return stream:
    # tracking error, information ratio, drawdown, and related review metrics.
    risk_statistics: Any = analytics.get_riskstatistics()
    written_paths.append(
        _write_html(output_directory, "risk_statistics.html", risk_statistics.to_html())
    )

    print("Open these files to review analytics output:")
    for path in written_paths:
        print(f"  {path.resolve()}")


def _load_analytics_settings() -> dict[str, Any]:
    """Return the Performance Analytics settings from the local YAML file."""
    with open(SPECIFICATIONS_PATH, "r", encoding=util.ENCODING) as file:
        config: Any = yaml.safe_load(file)
    if not isinstance(config, dict) or not isinstance(config.get("analytics"), dict):
        raise ValueError("ppar.yaml must contain an analytics mapping")
    return config["analytics"]


def _required_setting(settings: dict[str, Any], name: str) -> str:
    """Return one required non-empty string setting."""
    value = settings.get(name)
    if not isinstance(value, str) or not value:
        raise ValueError(f"analytics.{name} must be set in ppar.yaml")
    return value


def _frequency_from_string(value: str) -> Frequency:
    """Return the reporting frequency accepted by ``ppar analytics``."""
    normalized = value.strip().lower()
    if normalized.startswith("m"):
        return Frequency.MONTHLY
    if normalized.startswith("q"):
        return Frequency.QUARTERLY
    if normalized.startswith("y"):
        return Frequency.YEARLY
    raise ValueError("frequency must start with 'm', 'q', or 'y'")


def _write_html(output_directory: Path, file_name: str, html: str) -> Path:
    """Write one HTML review file.

    Args:
        file_name: Output file name under ``output/``.
        html: HTML document text to write.

    Returns:
        Path to the written HTML file.
    """
    path: Path = output_directory / file_name
    # ``exist_ok=True`` makes repeat runs overwrite output files without needing
    # manual cleanup between review cycles.
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding=util.ENCODING)
    return path


def _write_png(output_directory: Path, file_name: str, png: bytes) -> Path:
    """Write one PNG chart file.

    Args:
        file_name: Output file name under ``output/``.
        png: PNG image bytes returned by the chart renderer.

    Returns:
        Path to the written PNG file.
    """
    path: Path = output_directory / file_name
    # Chart renderers return PNG bytes, so ``write_bytes`` avoids any text
    # encoding assumptions.
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)
    return path


if __name__ == "__main__":
    main()
